//let test1 = require('./testQuery')
// let testRec = require('./testRec')
//let testParser = require('./testParser')
console.time('testForEach')
let testRec = require('./testPython')
console.timeEnd('testForEach')
